server:
  port: 8082
  servlet:
    context-path: /
spring:
  profiles:
    active: test
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.4:3306/test?useSSL=false&&charset=utf8&&loc=Asia%2FShanghai
    username: root
    password: 123123123
    name: test

  redis:
    database: 0
    host: 172.17.0.5
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 8
        #最小空闲ap
        min-idle: 0
    timeout: 10000ms

dubbo:
  config-center:
    protocol:zookeeper
    address:localhost:2181
  protocol:
    name:dubbo
    port:20880
  spring:
    config=classpath:dubbo-provider.xml

mybatis:
  type-aliases-package:  com.leepuvier
  mapper-locations: classpath:mappers/*.xml